"""
gdocs_tool.py
-------------
Creates a Google Doc execution report for a completed SecureIntent plan.

Requires:
  - google-api-python-client
  - google-auth-oauthlib
  - google-auth-httplib2

The user's google_refresh_token is used to authenticate on their behalf.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from loguru import logger


# Google Drive/Docs scopes needed (added to the OAuth login flow)
DOCS_SCOPES = [
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive.file",
]

# OAuth client credentials (same as Gmail/Calendar flow)
import os
GOOGLE_CLIENT_ID     = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
GOOGLE_TOKEN_URI     = "https://oauth2.googleapis.com/token"


def _build_creds(refresh_token: str) -> Credentials:
    """Build a google.oauth2.credentials.Credentials object from a refresh token."""
    return Credentials(
        token=None,
        refresh_token=refresh_token,
        token_uri=GOOGLE_TOKEN_URI,
        client_id=GOOGLE_CLIENT_ID,
        client_secret=GOOGLE_CLIENT_SECRET,
        scopes=DOCS_SCOPES,
    )


# ── Doc content helpers ────────────────────────────────────────────────────────

def _text_req(text: str, style: str = "NORMAL_TEXT") -> list[dict]:
    """Return a list of Docs API requests to insert styled text."""
    return [
        {
            "insertText": {
                "location": {"index": 1},
                "text": text,
            }
        },
        {
            "updateParagraphStyle": {
                "range": {"startIndex": 1, "endIndex": 1 + len(text)},
                "paragraphStyle": {"namedStyleType": style},
                "fields": "namedStyleType",
            }
        },
    ]


def _heading(text: str, level: int = 1) -> dict:
    return {"insertText": {"location": {"index": 1}, "text": text + "\n"}}


def _para(text: str) -> dict:
    return {"insertText": {"location": {"index": 1}, "text": text + "\n"}}


# ── Main export function ───────────────────────────────────────────────────────

def create_execution_report_doc(plan: dict, user_email: str, refresh_token: str) -> str:
    """
    Creates a Google Doc summarising the executed plan and returns its public URL.

    Args:
        plan: The plan row (from PLAN_CACHE or DB), including execution_log.
        user_email: The email of the executing user (for header info).
        refresh_token: The user's Google OAuth refresh token.

    Returns:
        A shareable Google Docs URL (e.g. https://docs.google.com/document/d/…/edit).
    """
    creds = _build_creds(refresh_token)
    docs_service = build("docs", "v1", credentials=creds, cache_discovery=False)
    drive_service = build("drive", "v3", credentials=creds, cache_discovery=False)

    plan_json  = plan.get("plan_json") or {}
    exec_log   = plan.get("execution_log") or []
    subject    = plan.get("subject") or plan_json.get("email_context", {}).get("subject", "(no subject)")
    sender     = plan.get("sender") or plan_json.get("email_context", {}).get("sender", "")
    goal_type  = (plan.get("goal_type") or "unknown").replace("_", " ").title()
    risk_level = (plan.get("risk_level") or "unknown").upper()
    risk_score = plan.get("risk_score")
    status     = plan.get("status", "unknown")
    created_at = plan.get("created_at", "")
    plan_id    = plan.get("id", "")

    # Format timestamp
    try:
        ts = datetime.fromisoformat(created_at.replace("Z", "+00:00")).strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        ts = created_at or "unknown"

    # ── 1. Create blank document ─────────────────────────────────────────────
    doc_title = f"SecureIntent Report — {subject[:60]}"
    doc = docs_service.documents().create(body={"title": doc_title}).execute()
    doc_id = doc["documentId"]

    # ── 2. Build content (inserted in reverse order because index=1 prepends) ─
    lines: list[str] = []

    lines.append("—" * 60 + "\n")
    lines.append(f"Generated by SecureIntent · {user_email}\n\n")

    # Step results
    lines.append("EXECUTION LOG\n\n")
    if exec_log:
        # Reverse loop for prepend logic, OR we use a different approach.
        # Since index=1 prepends, we should insert the last line first at index 1,
        # then the second to last line at index 1, and so on.
        # OR just reverse the entire list of lines at the end.
        
        # Let's collect them in a list and reverse at the end as done in the code.
        for i, step in enumerate(exec_log, 1):
            action  = str(step.get("action", "unknown")).replace("_", " ").upper()
            success = step.get("success", False)
            error   = step.get("error") or ""
            note    = step.get("note") or step.get("description") or ""
            status_icon = "✅" if success else "❌"
            lines.append(f"  Step {i}: {action}  {status_icon}\n")
            if note:
                lines.append(f"    Note: {note}\n")
            if error:
                lines.append(f"    Error: {error}\n")
        lines.append("\n")
    else:
        lines.append("  No step-level data recorded.\n\n")

    # Summary
    lines.append("PLAN SUMMARY\n\n")
    lines.append(f"  Plan ID    : {plan_id}\n")
    lines.append(f"  Status     : {status.upper()}\n")
    lines.append(f"  Goal Type  : {goal_type}\n")
    lines.append(f"  Risk Level : {risk_level}\n")
    if risk_score is not None:
        lines.append(f"  Risk Score : {risk_score:.1f}/100\n")
    lines.append(f"  Executed at: {ts}\n")
    lines.append(f"  Executed by: {user_email}\n\n")

    # Email context
    lines.append("EMAIL CONTEXT\n\n")
    lines.append(f"  Subject: {subject}\n")
    lines.append(f"  From   : {sender}\n\n")

    # Title / header
    lines.append("SECUREINTENT — EXECUTION REPORT\n\n")

    # Final order:
    # 1. Title
    # 2. Email Context
    # 3. Plan Summary
    # 4. Execution Log
    # 5. Footer
    
    # The code currently reverses them because it inserts at index 1.
    # To keep it simple, let's just use the reversed approach as intended.
    
    # Insert all text at once (prepended, so final order is correct)
    full_text = "".join(reversed(lines))

    requests = [
        {"insertText": {"location": {"index": 1}, "text": full_text}},
    ]

    # Apply heading style to first line
    requests.append({
        "updateParagraphStyle": {
            "range": {"startIndex": 1, "endIndex": len("SECUREINTENT — EXECUTION REPORT") + 1},
            "paragraphStyle": {"namedStyleType": "HEADING_1"},
            "fields": "namedStyleType",
        }
    })

    docs_service.documents().batchUpdate(
        documentId=doc_id,
        body={"requests": requests},
    ).execute()

    # ── 3. Make the document publicly readable (anyone with the link) ─────────
    drive_service.permissions().create(
        fileId=doc_id,
        body={"type": "anyone", "role": "reader"},
    ).execute()

    doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"
    logger.info("Execution report created: plan=%s url=%s", plan_id, doc_url)

    return doc_url
